status quo: Alan missing C# async
rust-lang/wg-async-foundations pull request #214
Opened 2021-05-28 18:00 UTC by Nashenas88

[Rendered](https://github.com/Nashenas88/wg-async-foundations/blob/f2cc60f61da71a3826dae686181845ba82662210/src/vision/status_quo/alan_misses_c_sharp_async.md)

I do have one todo left near the end. I wasn't sure if it was worth it to add an example of Alan trying to implement cancellation correctly or whether leaving it undone would show that it might be out of Alan's reach initially.

Also, should I add more C# examples earlier on to show where Alan is coming from?

2021-05-28 18:01 UTC, Nashenas88 commented on src/vision/status_quo/alan_misses_c_sharp_async.md
> +* [Niklaus] may not have had enough experience to be wary of some of the pitfalls encountered here.
I also wasn't sure if this was helpful to have here. I wouldn't expect someone new to programming to be familiar with these pitfalls, but is this too negative of a sentiment to have here?

2021-05-28 20:46 UTC, jbr commented
It might be interesting to hear how [stop-token](https://docs.rs/stop-token/0.2.0/stop_token/) (or, very similarly [stopper](https://docs.rs/stopper/0.2.0/stopper/)) meet the c# expectations of what a stop token does

2021-05-29 00:58 UTC, Nashenas88 commented
I've done a quick review and they look very promising. I'll extend the cancellation section with notes on those. I was surprised that none of those came up in my searches. I discovered that only the tokio one comes up lower in the search when I search `rust async cancellation`, but none of those show up when searching `rust cancel future` or `rust cancel async`.

2021-06-25 17:45 UTC, nikomatsakis requested changes
I think the morals could be made more precise! It feels like there are a number of sections here, each of which has a relatively precise moral. Can you note those down? 

For example, one thing I took away was "trying to use things from stdlib is obvious thing to try, but wrong because they are blocking"

2021-06-25 23:59 UTC, Nashenas88 commented
Sorry for amending the commit. I've been working in gerrit too much lately...

I expanded the cancellable section with an example usage of one of the libaries. I wasn't sure whether to extend it with the painful aspects of discovering `futures::select!` for the first time or not since that's not part of std.

I also fixed some typos in the C# cancellation example and expanded on the morals. Let me know if they're still too vague.

2021-06-26 06:39 UTC, tmandry commented
Ecosystem crates are definitely part of the status quo. But you might be able to link to [another story](https://rust-lang.github.io/wg-async-foundations/vision/status_quo/barbara_gets_burned_by_select.html) that mentions `select!`.

2021-06-26 06:45 UTC, tmandry approved these changes
Update looks good!

2021-07-09 17:21 UTC, merged

2021-07-09 17:21 UTC, nikomatsakis commented
Thanks @Nashenas88 !